server:
  port: 8762

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: aut
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: notification
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notification/**
        - id: examination
          uri: lb://EXAMINATION-SERVICE
          predicates:
            - Path=/api/v1/examination/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
  application:
    name: Gateway
management:
  endpoints:
    web:
      exposure:
        include: "*"